matrix:
  include:
    - language: php

      php:
        - '7.2'
      before_script:
        - cd api
        - composer install
      script:
        - php bin/phpunit
        - composer phpstan

    - language: node_js
      node_js:
        - "8"
      before_script:
        - cd web
      script:
        - npm i -g yarn
        - yarn
        - yarn test
