matrix:
  include:
    - language: php

      php:
        - '7.2'
      before_script:
        - cd api
        - composer install
      script:
        - php bin/phpunit

    - language: node_js

      before_script:
        - cd web
      script:
        - npm i -g yarn
        - yarn test
