nelmio_api_doc:
    documentation:
        info:
            title: Docker Cron Manager
            description: API Docs for the Docker Cron Manager
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
